name: Run Postman Tests with Newman
 
on:
  push:
    branches: [ main ]
  pull_request:
 
jobs:
  postman-tests:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
 
      - name: Install Newman
        run: npm install -g newman
 
      - name: Run Postman tests
        run: |
          newman run booker_postman_collection.json \
            --environment env_postman_booker.json
 